### ISSUE TITLE
关于动画...

### ISSUE THREAD

**Issue by EmbeddedAlchemist** [Eddddddddy/T12-PD-SolderingPen#1]
B站来的
您的项目应该是用Arduino开发的，用u8g2实现显示的吧
虽然我并不专业，但自认为有信心和能力帮您完成动画的部分
QQ1677712032

**Comment by Eddddddddy** [comment]
来了！

**Comment by hqs1** [comment]
LVGL yyds,但是328P的资源有点小，可能上ESP32这种主控比较舒服点

**Comment by Eddddddddy** [comment]
> LVGL yyds,但是328P的资源有点小，可能上ESP32这种主控比较舒服点

对，我是真的后悔用328p，资源太少了，还得单独给一个供电
